# Generated by Django 5.0.3 on 2024-04-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_products_image_producttypes_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='country',
        ),
    ]
