# Generated by Django 5.0.3 on 2024-04-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_city_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='users',
        ),
    ]
