# Generated by Django 5.0.3 on 2024-04-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
