# Generated by Django 5.0.3 on 2024-05-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_products_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
